# R: Loss Development Triangle and Reserving

## Import Libraries: tidyverse and ChainLadder

In [1]:
library(tidyverse)
suppressPackageStartupMessages(library(ChainLadder))
library(openxlsx)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
setwd("****")

## Data Processing

### 1. Read Data

In [3]:
data <- read_csv("ppauto_pos98-07.csv", show_col_types = FALSE)
head(data)

  GRCODE GRNAME                  AccidentYear DevelopmentYear DevelopmentLag
1 43     IDS Property Cas Ins Co 1998         1998            1
2 43     IDS Property Cas Ins Co 1998         1999            2
3 43     IDS Property Cas Ins Co 1998         2000            3
4 43     IDS Property Cas Ins Co 1998         2001            4
5 43     IDS Property Cas Ins Co 1998         2002            5
6 43     IDS Property Cas Ins Co 1998         2003            6
  IncurredLosses CumPaidLoss BulkLoss EarnedPremDIR EarnedPremCeded
1 50320          12762       21720    63709         3071
2 41036          26291        6514    63709         3071
3 39688          32420        2858    63709         3071
4 39278          36282         757    63709         3071
5 40647          38260        1444    63709         3071
6 40024          39122         426    63709         3071
  EarnedPremNet Single PostedReserves2007
1 60638         0      277117.7
2 60638         0      277117.7
3 60638         0      277117.7
4 60638         0      277117.7
5 60638         0      277117.7
6 60638         0      277117.7

### 2. User Input for a company

In [4]:
# ask user to type in an integer as company_id to locate a company
# id can be found in Excel sheet
company_id <- as.integer(readline(prompt = "Enter your name: "))
print(company_id)

Enter your name:  5

[1] 5

In [5]:
# create a list of companies
(company_list <- data %>% select ("GRNAME") %>% distinct() %>% pull())

  [1] "IDS Property Cas Ins Co"
  [2] "Celina Mut Grp"
  [3] "Federal Ins Co Grp"
  [4] "Buckeye Ins Grp"
  [5] "Employers Mut Co Of Des Moines"
  [6] "Farm Bureau Of MI Grp"
  [7] "Wawanesa Ins Grp"
  [8] "West Bend Mut Ins Grp"
  [9] "Secura Ins Co"
 [10] "Island Ins Cos Grp"
 [11] "Kentucky Farm Bureau Mut Ins Grp"
 [12] "Penn Miller Grp"
 [13] "American Modern Ins Grp Inc"
 [14] "Farmers Automobile Grp"
 [15] "Germania Ins Grp"
 [16] "State Farm Mut Grp"
 [17] "United Services Automobile Asn Grp"
 [18] "Farmers Alliance Mut & Affiliates"
 [19] "Oklahoma Farm Grp"
 [20] "Occidental Fire & Cas Co Grp"
 [21] "Aegis Grp"
 [22] "NC Farm Bureau Ins Grp"
 [23] "Florists Mut Ins Grp"
 [24] "FL Farm Bureau Grp"
 [25] "Grinnell Mut Grp"
 [26] "Cameron Mut Grp"
 [27] "Farmers Mtl Hail Ins Co Of Ia Grp"
 [28] "Amerisafe Grp"
 [29] "Tenn Farmers Mut"
 [30] "New Jersey Manufacturers Grp"
 [31] "Star Ins Grp"
 [32] "Pennsylvania Mfg Asn Ins Co"
 [33] "Farm Bureau Grp"
 [34] "Millers Mut Ins Assoc"
 [35] "Protective Ins Grp"
 [36] "Lumber Ins Cos"
 [37] "Nevada General Ins Co"
 [38] "Overseas Partners Us Reins Co"
 [39] "Agway Ins Co"
 [40] "All Nation Ins Co"
 [41] "Consumers Ins Usa Inc"
 [42] "Antilles Ins Co"
 [43] "Usauto Ins Co"
 [44] "Cornerstone Natl Ins Co"
 [45] "American Vehicle Ins Co"
 [46] "Eveready Ins Co"
 [47] "Yasuda Fire & Marine Ins Co Of Amer"
 [48] "First Amer Ins Co"
 [49] "Generali Us Branch"
 [50] "Homestead Ins Co"
 [51] "Ocean Harbor Cas Ins Co"
 [52] "Allegheny Cas Co"
 [53] "Badger Mut Ins Co"
 [54] "Partners Mut Ins Co"
 [55] "Brethren Mut Ins Co"
 [56] "Brotherhood Mut Ins Co"
 [57] "Chicago Mut Ins Co"
 [58] "Spartan Ins Co"
 [59] "Colorado Farm Bureau Mut Ins Co"
 [60] "US Lloyds Ins Co"
 [61] "Farmers Mut Ins Co Of NE"
 [62] "Fitchburg Mut Ins Co"
 [63] "Goodville Mut Cas Co"
 [64] "Hastings Mut Ins Co"
 [65] "IMT Ins Co Mut"
 [66] "Inland Mut Ins Co"
 [67] "Interboro Mut Ind Ins Co"
 [68] "Lebanon Mut Ins Co"
 [69] "Madison Mut Ins Co"
 [70] "Wea Prop & Cas Ins Co"
 [71] "Northwest Gf Mut Ins Co"
 [72] "Preferred Mut Ins Co"
 [73] "Southern Mut Ins Co"
 [74] "Standard Mut Ins Co"
 [75] "Sterling Ins Co"
 [76] "Wisconsin American Mut Ins Co"
 [77] "Wolverine Mut Ins Co"
 [78] "Maine Mut Fire Ins Co"
 [79] "Battle Creek Mut Ins Co"
 [80] "Wayne Mut Ins Co"
 [81] "Mennonite Mut Ins Co"
 [82] "German Mut Ins Co"
 [83] "Cooperativa D Seguros Multiples PR"
 [84] "Pioneer State Mut Ins Co"
 [85] "Pacific Ind Ins Co"
 [86] "Bancinsure Inc"
 [87] "Co-Operative Ins Co"
 [88] "Virginia Mut Ins Co"
 [89] "Bell United Ins Co"
 [90] "National Unity Ins Co"
 [91] "Springfield Fire & Cas Co"
 [92] "Harbor Ins Co"
 [93] "Southland Lloyds Ins Co"
 [94] "Vanliner Ins Co"
 [95] "Wellington Ins Co"
 [96] "Midwest Family Mut Ins Co"
 [97] "National American Ins Co"
 [98] "Mapfre Reins Corp"
 [99] "State-Wide Ins Co"
[100] "Peachtree Cas Ins Co"
[101] "Lancer Ins Co"
[102] "Gulf States Ins Co"
[103] "Century-Natl Ins Co"
[104] "Wisconsin Mut Ins Co"
[105] "Rockford Mut Ins Co"
[106] "Southwest General Ins Co"
[107] "Missouri Valley Mut Ins Co"
[108] "Federated Natl Ins Co"
[109] "Home State Cnty Mut Ins Co"
[110] "Old American Cty Mut Fire Ins Co"
[111] "Mountain West Farm Bu Mut Ins Co"
[112] "IFA Ins Co"
[113] "Haulers Ins Co Inc"
[114] "Middle States Ins Co Inc"
[115] "Nichido Fire & Marine Ins Co Ltd"
[116] "Star Cas Ins Co"
[117] "Alliance Mut Ins Co"
[118] "Dorinco Rein Co"
[119] "Seminole Cas Ins Co"
[120] "Rider Ins Co"
[121] "First American Specilaty Ins Co"
[122] "Nodak Mut Ins Co"
[123] "Center Mut Ins Co"
[124] "Agency Ins Co Of MD Inc"
[125] "Sirius Amer Ins Co"
[126] "New Jersey Citizens United Rcp Exch"
[127] "National Automotive Ins"
[128] "Pacific Specialty Ins Co"
[129] "Nissan Fire & Marine Ins Co Us Br"
[130] "Adriatic Ins Co"
[131] "Baltica-Skandinavia Rein Co Of Amer"
[132] "Pacific Pioneer Ins Co"
[133] "Seguros Triples Inc"
[134] "Interstate Auto Ins Co Inc"
[135] "Auto Club South Ins Co"
[136] "Armed Forces Ins Exchange"
[137] "Southern Group Ind Inc"
[138] "Toa-Re Ins Co Of Amer"
[139] "Nova Cas Co"
[140] "Traders Ins Co"
[141] "Atlantic Cas Ins Co"
[142] "San Antonio Reins Co"
[143] "American Hallmark Ins Co Of TX"

In [6]:
# print user's selected company for further reconciliation
print(paste("User input: ", company_list[company_id], sep = ""))

[1] "User input: Employers Mut Co Of Des Moines"

## Create Triangle Loss Data

### 1. Create Loss Triangle Data using triangle function in package ChainLadder

In [7]:
triangle_data <- data %>% 
                        filter(GRNAME == company_list[company_id], DevelopmentYear < 2008) %>% 
                        as.triangle( origin = "AccidentYear", dev = "DevelopmentLag", value = "IncurredLosses")

In [8]:
# view triangle data
triangle_data

            DevelopmentLag
AccidentYear 1     2     3     4     5     6     7     8     9     10
        1998 63183 60017 58684 58536 59547 59275 59436 59330 59008 58988
        1999 65785 61262 60196 60567 60649 59997 59939 59953 59960    NA
        2000 59571 54491 53932 53654 53710 53894 53879 53788    NA    NA
        2001 53875 50259 50119 50798 50202 50125 49962    NA    NA    NA
        2002 52373 51455 50903 50908 50500 50306    NA    NA    NA    NA
        2003 45696 47262 45548 44268 44429    NA    NA    NA    NA    NA
        2004 38756 38116 38594 38017    NA    NA    NA    NA    NA    NA
        2005 37148 35113 33511    NA    NA    NA    NA    NA    NA    NA
        2006 31881 30432    NA    NA    NA    NA    NA    NA    NA    NA
        2007 28721    NA    NA    NA    NA    NA    NA    NA    NA    NA

### 2. Create Loss Triangle Data Manually

In [9]:
# create triangle data by pivoting for validation
data %>% 
    filter(GRNAME == company_list[company_id], DevelopmentYear < 2008) %>% 
    select(AccidentYear, DevelopmentLag, IncurredLosses) %>% 
    pivot_wider(names_from = DevelopmentLag, values_from = IncurredLosses)

   AccidentYear 1     2     3     4     5     6     7     8     9     10
1  1998         63183 60017 58684 58536 59547 59275 59436 59330 59008 58988
2  1999         65785 61262 60196 60567 60649 59997 59939 59953 59960    NA
3  2000         59571 54491 53932 53654 53710 53894 53879 53788    NA    NA
4  2001         53875 50259 50119 50798 50202 50125 49962    NA    NA    NA
5  2002         52373 51455 50903 50908 50500 50306    NA    NA    NA    NA
6  2003         45696 47262 45548 44268 44429    NA    NA    NA    NA    NA
7  2004         38756 38116 38594 38017    NA    NA    NA    NA    NA    NA
8  2005         37148 35113 33511    NA    NA    NA    NA    NA    NA    NA
9  2006         31881 30432    NA    NA    NA    NA    NA    NA    NA    NA
10 2007         28721    NA    NA    NA    NA    NA    NA    NA    NA    NA

## Chain Ladder Modelling: using Mack's method

In [10]:
mack.cl <- MackChainLadder(triangle_data)
summary(mack.cl)

$ByOrigin
     Latest Dev.To.Date Ultimate        IBNR   Mack.S.E   CV(IBNR)
1998  58988    1.000000 58988.00     0.00000    0.00000        NaN
1999  59960    1.000339 59939.68   -20.32267   91.60327 -4.5074433
2000  53788    1.002988 53627.78  -160.22481  280.34036 -1.7496689
2001  49962    1.004048 49760.56  -201.44314  275.85550 -1.3693964
2002  50306    1.004386 50086.34  -219.65900  311.73257 -1.4191659
2003  44429    1.008097 44072.15  -356.85343  399.60517 -1.1198020
2004  38017    1.007130 37747.85  -269.14695  607.36351 -2.2566242
2005  33511    1.010597 33159.61  -351.38826  801.31762 -2.2804336
2006  30432    1.027345 29621.98  -810.01907 1002.90106 -1.2381203
2007  28721    1.074973 26717.88 -2003.12088 1671.42299 -0.8344094

$Totals
                  Totals
Latest:     4.481140e+05
Dev:        1.009898e+00
Ultimate:   4.437218e+05
IBNR:      -4.392178e+03
Mack S.E.:  2.590643e+03
CV(IBNR):  -5.898311e-01

### Ultimate Loss and IBNR

In [11]:
(output <- summary(mack.cl)$ByOrigin %>% rownames_to_column("AccidentYear"))

   AccidentYear Latest Dev.To.Date Ultimate IBNR        Mack.S.E   CV(IBNR)
1  1998         58988  1.000000    58988.00     0.00000    0.00000        NaN
2  1999         59960  1.000339    59939.68   -20.32267   91.60327 -4.5074433
3  2000         53788  1.002988    53627.78  -160.22481  280.34036 -1.7496689
4  2001         49962  1.004048    49760.56  -201.44314  275.85550 -1.3693964
5  2002         50306  1.004386    50086.34  -219.65900  311.73257 -1.4191659
6  2003         44429  1.008097    44072.15  -356.85343  399.60517 -1.1198020
7  2004         38017  1.007130    37747.85  -269.14695  607.36351 -2.2566242
8  2005         33511  1.010597    33159.61  -351.38826  801.31762 -2.2804336
9  2006         30432  1.027345    29621.98  -810.01907 1002.90106 -1.2381203
10 2007         28721  1.074973    26717.88 -2003.12088 1671.42299 -0.8344094

## Write Ouput to Excel Spreadsheet for Reconciliation

In [18]:
write.xlsx(output, file = "R_Output.xlsx", sheetName = "R")